# Generated by Django 4.2.4 on 2024-04-22 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registros',
            new_name='registro',
        ),
    ]
