# Generated by Django 4.2.4 on 2024-04-25 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_web', '0003_remove_registro_cantidad_registro_iva_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='registro_detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('folio', models.CharField(max_length=100)),
                ('subtotal', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('iva', models.FloatField(default=0)),
                ('emisor', models.CharField(max_length=15)),
                ('id_registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pagina_web.registro')),
            ],
        ),
    ]
