# Generated by Django 4.2.4 on 2024-04-25 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_web', '0004_registro_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
