# Generated by Django 4.2.4 on 2024-05-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_web', '0005_registro_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_detalle',
            name='receptor',
            field=models.CharField(default='1234567890987', max_length=15),
        ),
    ]
